name: Check RSS Feed and Build

on:
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  check-rss-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fetch RSS Feed
        uses: Promptly-Technologies-LLC/rss-fetch-action@v2
        with:
          feed_url: "https://www.radcrew.net/category/finalfantasy/feed"
          file_path: "./latest-feed.json"

      - name: Check if RSS feed has changed
        id: check_changes
        run: |
          if git diff --exit-code ./latest-feed.json; then
            echo "No changes detected in RSS feed"
            # Exit code 78 is a neutral exit code in GitHub Actions
            # It indicates that the job is skipped, not failed or succeeded
            exit 78
          else
            echo "Changes detected in RSS feed"
          fi

      - name: Commit and push changes to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update RSS feed"
          file_pattern: "*.json"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=jenovas-seo
